services:
  payment-lb:
    image: nginx:1.25-alpine
    container_name: payment-lb
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      payment-api-1:
        condition: service_healthy
      payment-api-2:
        condition: service_healthy
      payment-metrics-api:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  payment-api-1: &api
    container_name: payment-api-1
    hostname: payment-api-1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      PaymentProcessors__Default__BaseUrl: "http://payment-processor-default:8080"
      PaymentProcessors__Fallback__BaseUrl: "http://payment-processor-fallback:8080"
      JobsConfig__ProcessingBatchSize: 100
      JobsConfig__ProcessingParalellism: 10
      JobsConfig__ProcessingWaitMs: 40
      JobsConfig__PersistenceBatchSize: 200
      JobsConfig__PersistenceWaitMs: 20
      NetMQ__Host: "payment-metrics-api"
      NetMQ__Port: 5556
      NetMQ__Topic: "payments"
    depends_on:
       payment-metrics-api:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    healthcheck:
      test: [
        "CMD-SHELL",
        "curl --fail http://localhost:8080/healthz || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '125MB'

  payment-api-2:
    <<: *api
    container_name: payment-api-2
    hostname: payment-api-2

  payment-metrics-api:
    container_name: payment-metrics-api
    hostname: payment-metrics-api
    build:
      context: .
      dockerfile: Dockerfile.metrics
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      NetMQ__Host: "0.0.0.0"
      NetMQ__Port: 5556
      NetMQ__Topic: "payments"
    networks:
      - backend
      - payment-processor
    healthcheck:
      test: [
        "CMD-SHELL",
        "curl --fail http://localhost:8080/healthz || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '50MB'

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true